# Generated by Django 4.2.16 on 2025-12-05 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("GRACE", "Grace Period"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
