# Generated by Django 4.2.16 on 2025-12-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_sale_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_low_stock_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
