# Generated by Django 4.2.16 on 2025-12-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_last_low_stock_email_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="last_low_stock_email_sent_at",
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_alert_sent", models.DateTimeField(auto_now=True)),
                ("reminder_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product",)},
            },
        ),
    ]
